### PR TITLE
Radio Button

### PR DESCRIPTION
**Pull request by antony-mpokket**
Radio button changes

### CODE REVIEW

**Review by Antony-M1 — CHANGES_REQUESTED** [review]
everything is fine

**Comment by antony-mpokket** [comment]
> everything is fine

Thank you for the feedback

**Review by Antony-M1 — APPROVED** [review]

**Comment by Antony-M1** [comment]
thank you

**Comment by antony-mpokket** [comment]
Review is finished thatnk you

**Pull request merged**
